In [28]:
import pandas as pd
import numpy as np
# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 500) # To display all the columns of dataframe
pd.set_option('max_colwidth', None) # To set the width of the column to maximum
import warnings
warnings.filterwarnings("ignore")

In [29]:
df = pd.read_csv("Data_raw.csv")
df.head(5)

,Unnamed: 0,STT,Ngày tiếp nhận hồ sơ,Họ và tên,SĐT,Email,Prework,Đặc điểm ứng viên,Công ty hiện tại,Vị trí hiện tại,Ví trí có thể phù hợp,Unnamed: 10,Unnamed: 11,Tình trạng,Nguồn,FALSE,Mức độ tiềm năng
0,0,NaN,2021-07-09 00:00:00,Đinh Thị Nga,249166091,CSVSfmJHYibZg@gmail.com,NaN,Đã hẹn pv 15h ngày 9/9,NaN,NaN,NaN,NaN,NaN,Pass CV,NaN,False,NaN
1,1,NaN,2021-07-09 00:00:00,Nguyễn Thị Ngọc Anh,527356348,GmPinPpbxvWXS@gmail.com,NaN,Đã hẹn pv 10h ngày 9/9,NaN,NaN,NaN,NaN,NaN,Pass CV,NaN,False,NaN
2,2,NaN,2021-07-09 00:00:00,Nguyễn Thị Thu Trang,279398113,wGdXDagPrAnCO@gmail.com,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pass CV,NaN,False,NaN
3,3,NaN,2021-07-09 00:00:00,Đoàn Văn Tùng,381165239,wqeagQbimheri@gmail.com,NaN,Đã gửi thư cảm ơn,NaN,NaN,NaN,NaN,NaN,Pass CV,NaN,False,NaN
4,4,NaN,2021-07-09 00:00:00,Vũ Quỳnh Liên,808860383,fTXsgvuNNIBBG@gmail.com,NaN,Đã nhận việc ở cty khác,NaN,NaN,NaN,NaN,NaN,Pass CV,NaN,False,NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2423 entries, 0 to 2422
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             2423 non-null   int64
 1   STT                    0 non-null      float64
 2   Ngày tiếp nhận hồ sơ   1118 non-null   object
 3   Họ và tên              2049 non-null   object
 4   SĐT                    2423 non-null   int64
 5   Email                  2423 non-null   object
 6   Prework                5 non-null      object
 7   Đặc điểm ứng viên      1137 non-null   object
 8   Công ty hiện tại       0 non-null      float64
 9   Vị trí hiện tại        0 non-null      float64
 10  Ví trí có thể phù hợp  561 non-null    object
 11  Unnamed: 10            31 non-null     object
 12  Unnamed: 11            10 non-null     object
 13  Tình trạng             23 non-null     object
 14  Nguồn                  911 non-null    object
 15  FALSE                  2423 non-null   bool
 16  Mức độ tiềm năng       0 non-null      float64
dtypes: bool(1), float64(4), int64(2), object(10)
memory usage: 305.4+ KB

In [31]:
# Remove khoảng trắng 2 đầu trên mỗi column
df.columns = df.columns.str.strip()

In [32]:
# Đổi tên cột cho chuẩn
df.rename(columns={
    "Ví trí có thể phù hợp": "Vị trí phù hợp",
    "FALSE": "Đã liên hệ",  # hoặc xoá nếu không cần
    "Unnamed: 0": "ID",
}, inplace=True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2423 entries, 0 to 2422
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    2423 non-null   int64
 1   STT                   0 non-null      float64
 2   Ngày tiếp nhận hồ sơ  1118 non-null   object
 3   Họ và tên             2049 non-null   object
 4   SĐT                   2423 non-null   int64
 5   Email                 2423 non-null   object
 6   Prework               5 non-null      object
 7   Đặc điểm ứng viên     1137 non-null   object
 8   Công ty hiện tại      0 non-null      float64
 9   Vị trí hiện tại       0 non-null      float64
 10  Vị trí phù hợp        561 non-null    object
 11  Unnamed: 10           31 non-null     object
 12  Unnamed: 11           10 non-null     object
 13  Tình trạng            23 non-null     object
 14  Nguồn                 911 non-null    object
 15  Đã liên hệ            2423 non-null   bool
 16  Mức độ tiềm năng      0 non-null      float64
dtypes: bool(1), float64(4), int64(2), object(10)
memory usage: 305.4+ KB

In [34]:
# Loại bỏ các cột hoàn toàn rỗng (toàn NaN)
df.dropna(axis=1, how='all', inplace=True)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2423 entries, 0 to 2422
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    2423 non-null   int64
 1   Ngày tiếp nhận hồ sơ  1118 non-null   object
 2   Họ và tên             2049 non-null   object
 3   SĐT                   2423 non-null   int64
 4   Email                 2423 non-null   object
 5   Prework               5 non-null      object
 6   Đặc điểm ứng viên     1137 non-null   object
 7   Vị trí phù hợp        561 non-null    object
 8   Unnamed: 10           31 non-null     object
 9   Unnamed: 11           10 non-null     object
 10  Tình trạng            23 non-null     object
 11  Nguồn                 911 non-null    object
 12  Đã liên hệ            2423 non-null   bool
dtypes: bool(1), int64(2), object(10)
memory usage: 229.7+ KB

In [36]:
# Remove 2 column Unnamed: 10 và Unnamed: 11
df.drop(columns=["Unnamed: 10", "Unnamed: 11"], inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2423 entries, 0 to 2422
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   ID                    2423 non-null   int64
 1   Ngày tiếp nhận hồ sơ  1118 non-null   object
 2   Họ và tên             2049 non-null   object
 3   SĐT                   2423 non-null   int64
 4   Email                 2423 non-null   object
 5   Prework               5 non-null      object
 6   Đặc điểm ứng viên     1137 non-null   object
 7   Vị trí phù hợp        561 non-null    object
 8   Tình trạng            23 non-null     object
 9   Nguồn                 911 non-null    object
 10  Đã liên hệ            2423 non-null   bool
dtypes: bool(1), int64(2), object(8)
memory usage: 191.8+ KB

In [37]:
# Kiểm tra các cột quan trọng bị thiếu nhiều dữ liệu
missing_ratio = df.isnull().mean().sort_values(ascending=False)
print(missing_ratio)

Prework                 0.997936
Tình trạng              0.990508
Vị trí phù hợp          0.768469
Nguồn                   0.624020
Ngày tiếp nhận hồ sơ    0.538589
Đặc điểm ứng viên       0.530747
Họ và tên               0.154354
ID                      0.000000
Email                   0.000000
SĐT                     0.000000
Đã liên hệ              0.000000
dtype: float64

In [38]:
df.head()

,ID,Ngày tiếp nhận hồ sơ,Họ và tên,SĐT,Email,Prework,Đặc điểm ứng viên,Vị trí phù hợp,Tình trạng,Nguồn,Đã liên hệ
0,0,2021-07-09 00:00:00,Đinh Thị Nga,249166091,CSVSfmJHYibZg@gmail.com,NaN,Đã hẹn pv 15h ngày 9/9,NaN,Pass CV,NaN,False
1,1,2021-07-09 00:00:00,Nguyễn Thị Ngọc Anh,527356348,GmPinPpbxvWXS@gmail.com,NaN,Đã hẹn pv 10h ngày 9/9,NaN,Pass CV,NaN,False
2,2,2021-07-09 00:00:00,Nguyễn Thị Thu Trang,279398113,wGdXDagPrAnCO@gmail.com,NaN,NaN,NaN,Pass CV,NaN,False
3,3,2021-07-09 00:00:00,Đoàn Văn Tùng,381165239,wqeagQbimheri@gmail.com,NaN,Đã gửi thư cảm ơn,NaN,Pass CV,NaN,False
4,4,2021-07-09 00:00:00,Vũ Quỳnh Liên,808860383,fTXsgvuNNIBBG@gmail.com,NaN,Đã nhận việc ở cty khác,NaN,Pass CV,NaN,False

In [39]:
# Chuyển kiểu dữ liệu ngày tháng
df['Ngày tiếp nhận hồ sơ'] = pd.to_datetime(df['Ngày tiếp nhận hồ sơ'], errors='coerce')
df.head()

,ID,Ngày tiếp nhận hồ sơ,Họ và tên,SĐT,Email,Prework,Đặc điểm ứng viên,Vị trí phù hợp,Tình trạng,Nguồn,Đã liên hệ
0,0,2021-07-09,Đinh Thị Nga,249166091,CSVSfmJHYibZg@gmail.com,NaN,Đã hẹn pv 15h ngày 9/9,NaN,Pass CV,NaN,False
1,1,2021-07-09,Nguyễn Thị Ngọc Anh,527356348,GmPinPpbxvWXS@gmail.com,NaN,Đã hẹn pv 10h ngày 9/9,NaN,Pass CV,NaN,False
2,2,2021-07-09,Nguyễn Thị Thu Trang,279398113,wGdXDagPrAnCO@gmail.com,NaN,NaN,NaN,Pass CV,NaN,False
3,3,2021-07-09,Đoàn Văn Tùng,381165239,wqeagQbimheri@gmail.com,NaN,Đã gửi thư cảm ơn,NaN,Pass CV,NaN,False
4,4,2021-07-09,Vũ Quỳnh Liên,808860383,fTXsgvuNNIBBG@gmail.com,NaN,Đã nhận việc ở cty khác,NaN,Pass CV,NaN,False

In [42]:
# Remove hết khoảng trắng 2 đầu trong dữ liệu
for column in df.columns:
    if df[column].dtype == "object":
        df[column] = df[column].str.strip()
    else:
        pass